name: frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.2.1
  provider: ^6.0.1
  url_launcher: ^6.3.0
  web_socket_channel: ^3.0.0
  file_picker: ^8.0.3
  uuid: ^4.4.0
  pdfx: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg.jpg
    - assets/feed-the-database.pdf
